version: "3.8"
services:
  api:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
          - pgdb
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://moretech:techmore@pgdb:5432/moretech

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=moretech
      - POSTGRES_USER=moretech
      - POSTGRES_PASSWORD=techmore
    container_name: pgdb

    networks:
      - backend

    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: d0gied@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: whatdoesthefoxsay
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - pgdb
    networks:
      - backend

volumes:
  postgres-data:
  pgadmin:

networks:
  backend: