version: "3.8"
services:
  api:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
          - pgdb
    networks:
      - backend

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb

    networks:
      - backend

    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:

networks:
  backend: