version: "3.8"
services:
  api:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
  client:
   container_name: frontend
   build: 
    context: ./client
   ports:
     - "8001:8001"